# Generated by Django 4.2.30 on 2026-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='instagram',
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='ig_handle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='skills',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='years_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='specialty',
            field=models.CharField(default='', max_length=50),
        ),
    ]
