# Generated by Django 4.2.30 on 2026-05-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_masterprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprofile',
            name='specialty',
            field=models.CharField(choices=[('barber', 'Barber'), ('stylist', 'Hair Stylist'), ('nails', 'Nail Master'), ('makeup', 'Makeup Artist'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
