# Generated by Django 4.2.30 on 2026-06-19 13:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_masterprofile_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='cover_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='home_visits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Languages spoken — list of strings', size=None),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='pricing_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='studio_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='travel_radius_km',
            field=models.IntegerField(blank=True, help_text='Max km the master will travel for home visits', null=True),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='years_at_location',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='specialty',
            field=models.CharField(choices=[('barber', 'Barber'), ('stylist', 'Hair Stylist'), ('nails', 'Nail Master'), ('makeup', 'Makeup Artist'), ('tattoo', 'Tattoo Artist'), ('lash', 'Lash Artist'), ('brow', 'Brow Artist'), ('esthetics', 'Esthetician'), ('massage', 'Massage Therapist'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
