# Generated by Django 4.2.30 on 2026-06-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_masterprofile_avatar_url_masterprofile_cover_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Senior Barber"', max_length=120)),
                ('studio_name', models.CharField(blank=True, default='', help_text='e.g. "Iron & Comb Barbershop"', max_length=150)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('start_month', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('end_month', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text='I currently work here')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.masterprofile')),
            ],
            options={
                'ordering': ['-is_current', '-end_year', '-end_month', '-start_year', '-start_month'],
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Best Barber NYC 2023"', max_length=200)),
                ('issuer', models.CharField(blank=True, default='', help_text='e.g. "NYC Style Awards"', max_length=200)),
                ('year', models.IntegerField()),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honors', to='accounts.masterprofile')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Master Barber Diploma"', max_length=200)),
                ('institution', models.CharField(help_text='e.g. "NY Barber Academy"', max_length=200)),
                ('year', models.IntegerField()),
                ('file_url', models.URLField(blank=True, default='', help_text='Cloudinary URL of the cert scan', max_length=500)),
                ('file_kind', models.CharField(blank=True, default='', help_text='"image" or "pdf"', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.masterprofile')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
