# Generated by Django 4.2.30 on 2026-06-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_masterprofile_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveSmallIntegerField(help_text='How long this service takes (minutes)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in your local currency', max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, help_text='Optional photo of this service')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive services are hidden from clients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.masterprofile')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
