# Generated by Django 4.2.30 on 2026-06-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='concurrent_clients',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of clients you can handle simultaneously'),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='min_lead_time_hours',
            field=models.PositiveSmallIntegerField(default=2, help_text='Minimum hours between booking time and appointment'),
        ),
        migrations.CreateModel(
            name='UnavailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday, 6=Sunday — only for recurring blocks', null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Only for recurring blocks', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Only for recurring blocks', null=True)),
                ('reason', models.CharField(blank=True, help_text='Optional internal note: "Personal", "Vacation", etc.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_slots', to='accounts.masterprofile')),
            ],
            options={
                'ordering': ['start_datetime', 'weekday', 'start_time'],
            },
        ),
    ]
