# Generated by Django 4.2.30 on 2026-05-15 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(default='', max_length=100)),
                ('service', models.CharField(max_length=200)),
                ('category', models.CharField(default='', max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('generated_image', models.CharField(default='', max_length=300)),
                ('template_style', models.CharField(default='', max_length=50)),
                ('caption', models.TextField(default='')),
                ('hashtags', models.CharField(default='', max_length=500)),
                ('date', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='WorkPost',
        ),
    ]
