# Generated by Django 4.2.30 on 2026-05-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_delete_workpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='fmt',
            field=models.CharField(default='story', max_length=20),
        ),
    ]
