# Generated by Django 4.2.30 on 2026-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='master',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='datetime',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.CharField(default='2025-01-01', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='has_portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.CharField(default='00:00', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
    ]
