# Generated by Django 4.2.30 on 2026-06-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_masterprofile_concurrent_clients_and_more'),
        ('bookings', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, help_text='Public-facing booking ID like STBK-9F4K2', max_length=12, unique=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('client_notes', models.TextField(blank=True, help_text='Client preferences or special requests')),
                ('master_notes', models.TextField(blank=True, help_text="Master's private notes — never shown to client")),
                ('status', models.CharField(choices=[('pending_otp', 'Waiting for OTP'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('no_show', 'No-show'), ('cancelled', 'Cancelled'), ('refused', 'Refused by master')], db_index=True, default='pending_otp', max_length=24)),
                ('source', models.CharField(choices=[('direct_link', 'Direct link'), ('qr_code', 'QR code'), ('instagram', 'Instagram'), ('other', 'Other')], default='direct_link', max_length=24)),
                ('first_time_client', models.BooleanField(default=True, help_text='True if this email never booked with this master before')),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='When the 24h reminder email was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.masterprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.service')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_email', models.EmailField(db_index=True, max_length=254)),
                ('client_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_requests', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_email', 'created_at'], name='bookings_ot_client__27acd8_idx'), models.Index(fields=['client_ip', 'created_at'], name='bookings_ot_client__87996b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['master', 'start_time'], name='bookings_bo_master__4276fa_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client_email'], name='bookings_bo_client__ca5b55_idx'),
        ),
    ]
