# Generated by Django 4.2.30 on 2026-06-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_otprequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('direct_link', 'Direct link'), ('profile_link', 'Profile link'), ('qr', 'QR code'), ('instagram', 'Instagram'), ('other', 'Other')], default='direct_link', max_length=24),
        ),
    ]
